version: '3.2'
services:
    pg-obelisk:
        image: idragan/postgres-obelisk
        hostname: pg-obelisk1
        expose:
            - 5432
        ports:
            - "5435:5432"
        entrypoint: ["docker-entrypoint.sh", "-c", "config_file=/obelisk/conf/postgresql.conf"]
        environment:
                - POSTGRES_PASSWORD=opalpass
                - POSTGRESDATA_PASSWORD=opalpass
        volumes:
                - obelisk_data1:/obelisk/data
                  # added pgdata volume to separate it from the main container  
                - ./postgresql.conf:/obelisk/conf/postgresql.conf
        shm_size: '1gb'



    rock-obelisk:
        image: obiba/rock:latest
        hostname: rock-obelisk1
        environment:
            - JAVA_OPTS=-Xms32m -Xmx512m -XX:+UseG1GC
        expose:
          - 8085

    opal-obelisk:
        image: idragan/opal-obelisk
        hostname: opal-obelisk1
        expose:
            - 8443
            - 8080
        ports:
            - "7843:8443"
            - "7880:8080"
            # Ports convention: <port on host>:<port inside container>
        links:
            - pg-obelisk
            - rock-obelisk  
        environment:
            - JAVA_OPTS=-Xms32m -Xmx512m -XX:+UseG1GC
            - OPAL_ADMINISTRATOR_PASSWORD=password
            - ROCK_HOSTS=rock-obelisk1:8085
            - POSTGRESIDS_HOST=pg-obelisk1
            - POSTGRESIDS_DATABASE=opal_id
            - POSTGRESIDS_USER=opal
            - POSTGRESIDS_PASSWORD=opalpass  
            - POSTGRESDATA_HOST=pg-obelisk1
            - POSTGRESDATA_DATABASE=opal_data
            - POSTGRESDATA_USER=opal
            - POSTGRESDATA_PASSWORD=opalpass  
                
volumes:
    obelisk_data1:
