version: '3.2'
services:
    opal-obelisk:
        image: idragan/opal-obelisk
        hostname: opal-obelisk1
        expose:
            - 8443
            - 8080
        ports:
            - "7843:8443"
            - "7880:8080"
            # Ports convention: <port on host>:<port inside container>
        environment:
            - JAVA_OPTS=-Xms32m -Xmx512m -XX:+UseG1GC
            - OPAL_ADMINISTRATOR_PASSWORD=$OPAL_ADMIN_PASS
            - ROCK_HOSTS=$ROCK_HOSTS
            - POSTGRESIDS_HOST=$PG_HOST
            - POSTGRESIDS_DATABASE=opal_id
            - POSTGRESIDS_USER=opal
            - POSTGRESIDS_PASSWORD=$OPAL_PG_PASS  
            - POSTGRESDATA_HOST=$PG_HOST
            - POSTGRESDATA_DATABASE=opal_data
            - POSTGRESDATA_USER=opal
            - POSTGRESDATA_PASSWORD=$OPAL_PG_PASS  
                
