version: '3.2'
services:
    pg-obelisk:
        image: idragan/postgres-obelisk
        hostname: pg-obelisk1
        expose:
            - 5432
        ports:
            - "5435:5432"
        entrypoint: ["docker-entrypoint.sh", "-c", "config_file=/obelisk/conf/postgresql.conf"]
        environment:
                - POSTGRES_PG_PASSWORD=$POSTGRES_PG_PASS
                - OPAL_PG_PASSWORD=$OPAL_PG_PASS
        volumes:
                - obelisk_data1:/obelisk/data
                  # added pgdata volume to separate it from the main container  
                - ./postgresql.conf:/obelisk/conf/postgresql.conf
        shm_size: '1gb'



