version: '3.2'
services:
  rock-obelisk:
      image: obiba/rock:latest
      hostname: rock-obelisk1
      networks: 
          - obelisk
      environment:
          - JAVA_OPTS=-Xms32m -Xmx512m -XX:+UseG1GC
          - ROCK_USER_NAME=$ROCK_USER
          - ROCK_USER_PASSWORD=$ROCK_PASS
          - ROCK_OPAL_SERVER=opal-obelisk1:7880
          - ROCK_SERVER=rock-obelisk1:8085
          - ROCK_OPAL_TOKEN=$ROCK_OPAL_TOKEN
      expose:
          - 8085
      ports:
          - "8085:8085"
      volumes:
          - rock-library1:/var/lib/rock/R/library

volumes:
    rock-library1:

networks:
  obelisk:
    external: true
