version: '3.2'
services:
    opal-obelisk:
        image: idragan/opal-obelisk
        hostname: opal-obelisk1
        expose:
            - 8443
            - 8080
        ports:
            - "7843:8443"
            - "7880:8080"
        environment:
            - JAVA_OPTS=-Xms32m -Xmx512m -XX:+UseG1GC
            - OPAL_ADMINISTRATOR_PASSWORD=$OPAL_ADMIN_PASS
            - ROCK_HOSTS=localhost:8085
            - POSTGRESIDS_HOST=$PG_HOST
            - POSTGRESIDS_DATABASE=opal_id
            - POSTGRESIDS_USER=opal
            - POSTGRESIDS_PASSWORD=$OPAL_PG_PASS  
            - POSTGRESDATA_HOST=$PG_HOST
            - POSTGRESDATA_PORT=$PG_PORT
            - POSTGRESDATA_DATABASE=opal_data
            - POSTGRESDATA_USER=opal
            - POSTGRESDATA_PASSWORD=$OPAL_PG_PASS  
            - ROCK_USER_USER=$ROCK_USER
            - ROCK_USER_PASSWORD=$ROCK_PASS    
            - ROCK_OPAL_TOKEN=$ROCK_OPAL_TOKEN

