version: '3.2'
services:

    pg-obelisk:
        image: idragan/postgres-obelisk
        hostname: postgres1
        expose:
            - 5432
        ports:
            - "5435:5432"
        entrypoint: ["docker-entrypoint.sh", "-c", "config_file=/obelisk/conf/postgresql.conf"]
        environment:
                - POSTGRES_PASSWORD=opalpass    
        volumes:
                - obelisk_data1:/obelisk/data         
                - ./postgresql.conf:/obelisk/conf/postgresql.conf
        shm_size: '1gb'          




volumes:
    obelisk_data1:
